language: python
python:
  - "3.7"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
script:
  - pytest -v --cov app --cov-report term-missing
after_success:
  - coveralls

notifications:
  email: false