language: python
python:
  - "3.6"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
script:
  # - pytest -v --cov app --cov-report term-missing
  - pytest --cov
  - coverage
  - coverage3 report
  - coveralls
after_success:
  - coveralls

notifications:
  email: false